# 密码相关的敏感信息规则
password-variable:
  description: 变量名中包含 password 等字样的敏感信息
  message: 发现硬编码密码风险
  severity: CRITICAL
  key:
    regex: ^\S*(passwords?|passwd|pass|pwd)_?(hash)?[0-9]*$
    ignorecase: True
  value:
    minlen: 5
